DECLARE
V_COUNT INTEGER;
BEGIN
SELECT COUNT(TABLE_NAME) INTO V_COUNT from USER_TABLES where TABLE_NAME = '__EFMigrationsHistory';
IF V_COUNT = 0 THEN
Begin
BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"__EFMigrationsHistory" (
    "MigrationId" NVARCHAR2(150) NOT NULL,
    "ProductVersion" NVARCHAR2(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
)';
END;

End;

END IF;
EXCEPTION
WHEN OTHERS THEN
    IF(SQLCODE != -942)THEN
        RAISE;
    END IF;
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"AppUsers" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "FullName" NVARCHAR2(150) NOT NULL,
    "PhoneNumber" NVARCHAR2(20) NOT NULL,
    "Email" NVARCHAR2(100) NOT NULL,
    "Address1" NVARCHAR2(2000) NOT NULL,
    "Address2" NVARCHAR2(2000),
    "LoyaltyPoints" NUMBER(10) NOT NULL,
    CONSTRAINT "PK_AppUsers" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Categories" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "Name" NVARCHAR2(100) NOT NULL,
    "Description" NVARCHAR2(2000),
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Promotions" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "Code" NVARCHAR2(50) NOT NULL,
    "DiscountPercentage" decimal(18,2) NOT NULL,
    "MaxUsage" NUMBER(10) NOT NULL,
    "CurrentUsage" NUMBER(10) NOT NULL,
    "ExpiryDate" TIMESTAMP(7) NOT NULL,
    "IsActive" BOOLEAN NOT NULL,
    CONSTRAINT "PK_Promotions" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Products" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "CategoryId" NUMBER(10) NOT NULL,
    "Name" NVARCHAR2(200) NOT NULL,
    "Description" NVARCHAR2(2000),
    "Price" decimal(18,2) NOT NULL,
    "StockQuantity" NUMBER(10) NOT NULL,
    "Origin" NVARCHAR2(2000),
    "IsHot" BOOLEAN NOT NULL,
    "IsAvailable" BOOLEAN NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Product_StockQuantity" CHECK ("StockQuantity" >= 0),
    CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Orders" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "UserId" NUMBER(10) NOT NULL,
    "PromotionId" NUMBER(10),
    "OrderDate" TIMESTAMP(7) NOT NULL,
    "TotalAmount" decimal(18,2) NOT NULL,
    "PaymentMethod" NVARCHAR2(2000) NOT NULL,
    "Status" NVARCHAR2(2000) NOT NULL,
    "ShipperId" NUMBER(10),
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_AppUsers_ShipperId" FOREIGN KEY ("ShipperId") REFERENCES "AppUsers" ("Id"),
    CONSTRAINT "FK_Orders_AppUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AppUsers" ("Id"),
    CONSTRAINT "FK_Orders_Promotions_PromotionId" FOREIGN KEY ("PromotionId") REFERENCES "Promotions" ("Id") ON DELETE SET NULL
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"OrderDetails" (
    "OrderId" NUMBER(10) NOT NULL,
    "ProductId" NUMBER(10) NOT NULL,
    "Quantity" NUMBER(10) NOT NULL,
    "UnitPrice" decimal(18,2) NOT NULL,
    CONSTRAINT "PK_OrderDetails" PRIMARY KEY ("OrderId", "ProductId"),
    CONSTRAINT "FK_OrderDetails_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrderDetails_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id")
)';
END;
/

CREATE INDEX "IX_OrderDetails_ProductId" ON "OrderDetails" ("ProductId")
/

CREATE INDEX "IX_Orders_PromotionId" ON "Orders" ("PromotionId")
/

CREATE INDEX "IX_Orders_ShipperId" ON "Orders" ("ShipperId")
/

CREATE INDEX "IX_Orders_UserId" ON "Orders" ("UserId")
/

CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId")
/

CREATE UNIQUE INDEX "IX_Promotions_Code" ON "Promotions" ("Code")
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20260721032056_InitialCreate', N'8.0.3')
/

